apiVersion: apps/v1
kind: Deployment
metadata:
  name: walterbob
  labels:
    app: walterbob
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: walterbob
  template:
    metadata:
      name: walterbob
      labels:
        app: walterbob
    spec:
      containers:
        - name: walterbob
          image: victormilk/walterbob
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
      
