apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: walterbob-hpa
  namespace: walterbob-dev
  labels:
    app: walterbob
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: walterbob
  minReplicas: 1
  maxReplicas: 4
  metrics:

    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80