apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

namespace: walterbob-dev

images:
  - name: victormilk/walterbob
    newTag: c1a112ea3551b60c84078aa49ffee9e3657f7f43
