apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml

namespace: walterbob

images:
  - name: victormilk/walterbob
    newTag: 8eabb8b8a63b22b9f186e08d9c1a4992707d67c2
